import numpy as np

def transform_covariates(covariates, n_bins):
    """
    Returns a transformed version of covariates where each value is replaced by the mean of 
        their respective binned group

    Parameters
    -------
    covariates : list of covariates to be transformed, currently being continuous
    n_bins : the number of ordinal variables the covariates are to be transformed into
    -------

    Returns
    -------
    transformed_covariates : list of transformed covariates, where each value is generated by
        first sorting the covariates input, binning everything into n_bins and replacing each
        value by the mean within the bin.
    -------
    """

    covariates = np.array(covariates)
    argsort = np.argsort(covariates)
    orders = np.array_split(argsort, n_bins)
    
    for order in orders:
        covariates[order] = covariates[order].mean()
    
    return covariates





